#pragma once

constexpr const char *help_message = "\n-----This is guide how to use"
" <serials tool>-----------------\n"
"Version:\t0.0.2\n"
"Released:\t9.01.2025\n"
"-------------------------------------------------------------\n"
"\nAvailable serials:\n"
"-------------------------------------------------------------\n"
"-a\tAccording To Jim;\n"
"-b\tBrassic;\n"
"-h\tHow I Met Your Mother;\n"
"-s\tSilicon Valley;\n"
"-t\tTwo And A Half Men\n"
"-bbt\tThe Big Bang Theory\n"
"-p\tPoor People\n"
"-n\tNew Girl\n"
"--------------------------------------------------------------\n"
"Usage example:\n"
"serials -a\t opens According To Jim sitcom\n"
"Note! param -a doesn't work with params -[lang] and -[season]\n"
"because this site doesn't allow to switch between languages\n"
"and seasons programmaticaly.\n"
"\nUsage example #2:\n"
"serials -b -3 opens sitcom Brassic season 3 (russian audio),\n"
"but if you want to watch with original audio you have to\n"
"specify if in command line like this:\n"
"serials -b -3 -e\t,where -e is a parameter\n"
"for original (english) audio.\n"
"More over you are allowed to specify -r, what means\n"
"russian audio. But it's unneccessary.\n\n"
"Additional commands:\n"
"#1. For displaying an amount of serials in current version\n"
"\ttype following command:\tserials --serials\n"
"#2. For displaying amount of seasons in desired serial\n"
"\ttype following command:\tserials -<serial symbol> --list\n"
"--------------------------------------------------------------\n\n"
;